# Configurando o spring falando que teremos um banco h2 com o nome
# sdw2023 e username sdw2023 sem senha
spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password:

# Aqui temos algumas configurações para deixar as Queries mais verbosas,
# onde será possível visualizá-las pelo log
# ddl como create é para pedir para o hibernate criar as tabelas em
# um primeiro momento.
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true

# Configuramos o h2 para termos acesso a seu console, podendo acessar o
# banco de dados via browser.
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
